language: node_js
node_js:
  - node
  - lts/*
branches:
  only:
    - master
    - /v\d+\.\d+/
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
after_script:
  - npx codecov
notifications:
  email: false
deploy:
  provider: npm
  email: notcaseywebb@gmail.com
  api_key:
    secure: hSWU44fYzrlWFrCEPtgVrMP6Pk4QuOoNl7vZtWvu7GoilFA00mYiG6DbQPjY3ju394k8usQLTUhkSvYl//vwgdAen6oNwlMzYiO6tae8+eidmOLn3TjfXfT5uFnD3zXZ+5JKIR1DTNgkdloJpbUiAMXg7KBa2exUVLdQhFpTnv/eR/AxUgLkyVjJQpjY63eEX0j4+eiYbmDCW6BSesIYjveZpS9sydNL2K1clBkPTrl9FkQ6qeIkXTxALCPwV17aXJYFOqiekgnqjn1RdycFzFd2zfZ/TDvCVhybxT8OSTG7b82pA/500QmO0bLxyXqreQVV0gm4YnQYkFMQjnZ8QmNkvjVQ1Kvzb2euiRM+zztxuCmk4FW9mqOFHfK0t9MYXLQ131KFn4q/8asrXlQrpr2HsP77/frbx3VvBRlMj5F91KLCM9AqQQB+yfzLa8uaMnyZj4FXdW/0+BIiWVFbhC/qYpPz4iaSZdJnSBiEK3BUw1bdXvrv74CoJ9LvA6b0tLbedBpmxJawC1qwsgciveHm/RMnVS5PONLWQU19mZZ7QOfMfkO5ibQ3nFKnTJiGAd4FGG8BSdm4MbmqlimrhPyt77idGWdiN8YFdFplwk/gZq5JB7mainggySxgwDO+BSheKAZ8PsKYWH+CVKWCQOVqKTpqgrwUwmjIZHcLN1s=
  on:
    tags: true
    repo: caseyWebb/taskr-filter
